### ISSUE TITLE
Staticman v2 error: Too many requests in this time frame

### ISSUE THREAD

**Issue by VincentTam** [dancwilliams/networkhobo#373]
![screenshot from 2018-11-14 21-33-36](https://user-images.githubusercontent.com/5748535/48510926-85d51a80-e855-11e8-8e24-ea4ce1d93a5f.png)

This reminds me eduardoboucas/staticman#222 and eduardoboucas/staticman#227.  I suspect that the public production instance of Staticman v2 is hosted on a paid Heroku dyno and that the server is hitting the limits of his Heroku billing plan.

Here's the comment that I intend to leave under your great post about nested Staticman comments.
* * *
Test reply to Dan.

I think the "In reply to `<name>`" contains a *logic error*.  When the "reply to thread button is clicked, the `changeValue` function only sets `reply_to` to `_id` of the head of the thread, and the `parentName` is tied with `parentId`.  In one single thread, there's *only one* head (i.e. `parentId`), but it may have *multiple* participants (i.e. `parentName`).

Nonetheless, I've learnt a lot from your explanations.  Thanks for this great article!

**Comment by dancwilliams** [comment]
Thanks for the great comment! I will sit down and give this a look.

**Comment by VincentTam** [comment]
I've just published a [pre-release of my fork of Beautiful Hugo](https://github.com/VincentTam/beautifulhugo/releases/tag/reply-rc1.1) and built [an demo site on GitLab](https://vincenttam.gitlab.io/bhdemo), thanks to [your great tutorial](https://networkhobo.com/2017/12/30/hugo-staticman-nested-replies-and-e-mail-notifications/).

**Comment by dancwilliams** [comment]
@VincentTam 

Ugh...I am finally getting around to reviewing this code and your pull request on Beautiful Hugo.  You have done some great stuff.  I am going to work on integrating it into my setup over the next few days.

I put Staticman into my blog before someone built it into Beautiful Hugo and just never circled back.  I am glad you found my blog useful.  I know very little about forms and was learning Go templating on the fly, so thanks for taking my madness and making it clean!

**Comment by VincentTam** [comment]
Looking back, the code for the reply target anchor in a comment reply can be much simpler if the id attribute for the article tag which wraps the comment is set to be the comment id in the YML file.  This makes the link of a post comment much more stable than the current approach (`id=comment-1`).  I *didn't* implement this in halogenica/beautifulhugo#222 because that would break the existing links to comments.  However, you may further simplify my code by getting rid of the JS code for smooth scrolling, which I added to alter the behavior of the anchor.
